language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON * . * TO 'root'@'localhost';"
  - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS twitch"
  - mysql -uroot twitch < schema.sql
  - cp src/config/config_example.py src/config/config.py
  - cp globals_example.py globals.py
  - sudo apt-get install mysql-server
  - sudo service mysql restart
# command to run tests
script: python -m unittest discover
